### ISSUE TITLE
💔 ERROR: Version number has increased since previous release on Google Fonts?

### ISSUE THREAD

**Issue by kosbarts** [kosbarts/Commissioner#26]
💔 ERROR The condition FontBakeryCondition:api_gfonts_ttFont had an error: FailedConditionError: The condition FontBakeryCondition:remote_styles had an error: FailedConditionError: The condition FontBakeryCondition:familyname_with_spaces had an error: TypeError: expected string or bytes-like object

**Comment by kosbarts** [comment]
@felipesanches Commissioner has not yet been released. Should there be an ERROR reported here or should it just skip this somehow?

**Comment by felipesanches** [comment]
if you get an ERROR, it means fontbakery is broken. Please make sure you're using the latest version of fontbakery (0.7.24) and, if so, please report the ERROR on fontbakery's issue tracker.

If you're using an older version, please update the installation to see if the bug was already fixed on the newest version.
